version : '3.7'

services:
  mysql:
    image: mysql:5.7
    container_name: dev_mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - TZ=Asia/Jakarta
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DB_NAME:-database}
      - MYSQL_USER=${DB_USER:-user}
      - MYSQL_PASSWORD=${DB_PASS:-user}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80